### ISSUE TITLE
Some questions about Dataset

### ISSUE THREAD

**Issue by VictoryLoveJessica** [Zielon/MICA#10]
Thx for your great work!
I downloaded some of the eight datasets mentioned in your document.
But I can't get the subset zip file which format is 
root\
    FLAME_parameters\
        actor_id\
            *.npz
    registrations\
        actor_id\
            *.obj

Would you like to tell me how to get this subset zip file? Generating by myself?

Thanks a lot!

**Comment by Zielon** [comment]
Hello, the `*.zip` files will be uploaded by the owners of the original datasets. There is a possibility that they haven't uploaded them yet. The FRGC dataset you can request from us directly following the [https://github.com/Zielon/MICA/tree/master/datasets/#frgc-subset](instructions).

**Comment by VictoryLoveJessica** [comment]
Thx a lot! I got it!

**Comment by VictoryLoveJessica** [comment]
Hello, I have already sent the license agreement of Florence and Stirling Datasets to your email: mica [AT] tue.mpg.de. The holders of these two datasets do not have the MICA format data：
root
FLAME_parameters
actor_id
*.npz
registrations
actor_id
*.obj

Would you please share these two MICA format data with me by email(link)? Thanks a lot!

**Comment by Zielon** [comment]
Hello, we contacted the holders of Stirling Dataset, we will do the same for Florence. The dataset should be soon available from their website.

**Comment by VictoryLoveJessica** [comment]
😀Hi! What's the latest progress about these datasets? Thx a lot!

**Comment by shuishiwojiade** [comment]
> 😀Hi! What's the latest progress about these datasets? Thx a lot!

Much of the subset data in the URL links is not in the format required by MICA.
In order to obtain this dataset, I need to send the license agreement to the original data author or to MICA author ？

**Comment by Zielon** [comment]
We again contacted the dataset owners. Hopefully, soon the situation will be clear.

**Comment by VictoryLoveJessica** [comment]
> > 😀Hi! What's the latest progress about these datasets? Thx a lot!
> 
> Much of the subset data in the URL links is not in the format required by MICA. In order to obtain this dataset, I need to send the license agreement to the original data author or to MICA author ？

 The original data author

**Comment by VictoryLoveJessica** [comment]
> We again contacted the dataset owners. Hopefully, soon the situation will be clear.

Thanks a lot! Please check the mica-email, which we sent you an email of the FRGC license. Could you please send the image data and the MICA-format data to us by email?  

Thanks again
