### ISSUE TITLE
How to get the 7 keypoints ?

### ISSUE THREAD

**Issue by zhengqudubo** [Zielon/MICA#11]
Hello, there is no keypoints file after running demo. Could you please provide  the 7 keypoints ?

**Comment by Zielon** [comment]
Now the 7 keypoints will be saved in the demo output folder.
https://github.com/Zielon/MICA/blob/master/demo.py#L140

**Comment by zhengqudubo** [comment]
> Now the 7 keypoints will be saved in the demo output folder. https://github.com/Zielon/MICA/blob/master/demo.py#L140

Thank you !

**Comment by AyushP123** [comment]
@Zielon Can these landmarks be used directly for NoW benchmark?

**Comment by Zielon** [comment]
Yes.
