### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by lzqfdd** [Zielon/MICA#15]
RuntimeError: Failed downloading url http://insightface.cn-sh2.ufileos.com/models/antelopev2.zip

**Comment by lzqfdd** [comment]
The display file opened according to the web address does not exist.

**Comment by lzqfdd** [comment]
@ @ @ @

**Comment by Zielon** [comment]
You can get them from https://github.com/Zielon/MICA#pre-trained-models
