### ISSUE TITLE
CUDA 10.1

### ISSUE THREAD

**Issue by gabriel-lucas** [Zielon/MICA#16]
Hi,

Thanks for the nice work you share, I find it very interesting.

I´m trying to install it but I found that I´m running a different cuda version 10.1.

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

The [environment.yml](https://github.com/Zielon/MICA/blob/master/environment.yml) in the repository installs newer version of cudatoolkit (11.3.1=h2bc3f7f_2) and this ends up in a pytorch3d error when running demo.py.

```
from pytorch3d import _C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
```

It looks related with this.
https://github.com/facebookresearch/pytorch3d/issues/1013#issuecomment-1006431449

Some packages versions should be changed to adapt to the cuda version.

Could someone point me in the right direction?

Best regards.

**Comment by lzqfdd** [comment]
Hello, are you also running this code? When you encounter that problem, you can try to create an environment first, and then install CUDA according to your server to see if it is compatible. The premise is that this code supports older CUDA versions. I have a problem that I have downloaded antelopev2, but I still go back to the website to download it when running. Have you met? If you encounter the same error, can you help me solve it? Thank you.

**Comment by Zielon** [comment]
The env file is using a nightly version of pytorch3d because I had problems with my RTX3090. One of the solutions would be to remove `pytorch3d-nightly` from dependency and install if from the `pytroch3d` channel also adapting the cuda toolkit version.

**Comment by gabriel-lucas** [comment]
Thanks @Zielon, you were of great help :)

I tested your proposal and it worked flawlessly.

**Comment by gabriel-lucas** [comment]
I think it´s better if you open a new issue describing problem you are facing in detail.


> Hello, are you also running this code? When you encounter that problem, you can try to create an environment first, and then install CUDA according to your server to see if it is compatible. The premise is that this code supports older CUDA versions. I have a problem that I have downloaded antelopev2, but I still go back to the website to download it when running. Have you met? If you encounter the same error, can you help me solve it? Thank you.
