### ISSUE TITLE
Questions About Face Tracking

### ISSUE THREAD

**Issue by VictoryLoveJessica** [Zielon/MICA#17]
Would you please tell me how to avoid the face-shaking problem of Face2Face? I think the expression parameters of each frame cause the face-shaking in the reconstructed video.

**Comment by Zielon** [comment]
You could try to add temporal smoothing. Either as a post-processing step or during optimization by minimizing for instance `(e_t0 - e_t1)` where `e_t` is for example expressions parameters for a time stamp.

**Comment by VictoryLoveJessica** [comment]
Thanks for your reply. I have two more questions to ask:
1) Would you please tell me more details about the temporal smoothing method?

2) I want to know whether such smoothing will change the specific value of expression parameters, resulting in an inaccurate reconstruction effect.

Thanks a lot!

**Comment by Zielon** [comment]
1) I think there are a lot of sources where you could read about smoothing, moving average, etc.

**Comment by Zielon** [comment]
https://github.com/Zielon/metrical-tracker
