### ISSUE TITLE
insightface has not app.py ang utils.pu

### ISSUE THREAD

**Issue by lhh753159** [Zielon/MICA#19]
demo.py use from insightface.app import FaceAnalysis ; from insightface.app.common import Face; from insightface.utils import face_align, but I cannot find the app.py and utils.py

**Comment by Jimmy142857** [comment]
pip install insightface

**Comment by lhh753159** [comment]
under the insightface dir is the./model, and under the ./model  is ./antelopev2 and ./buffalo_l which has some .onnx . I can not find 'insightface.app import FaceAnalysis' and 'insightface.app.common import Face', could you tell me how get them?
