### ISSUE TITLE
Hi, seems insight face perttrained model not found

### ISSUE THREAD

**Issue by jinfagang** [Zielon/MICA#2]
```
{"RetCode":-148654, "ErrMsg":"file not exist"}
```

http://insightface.cn-sh2.ufileos.com/models/antelopev2.zip

Someone deleted it? any copy?

**Comment by Zielon** [comment]
Hey, the `install.sh` will download it automatically. You can also download them from here:
```
antelopev2.zip from https://keeper.mpdl.mpg.de/f/2d58b7fed5a74cb5be83/?dl=1
buffalo_l.zip from https://keeper.mpdl.mpg.de/f/8faabd353cfc457fa5c5/?dl=1
```

then you need to unzip then and place in `~/.insightface/models/`

**Comment by affromero** [comment]
Modifying the demo for a different `insightface` folder location:
https://github.com/Zielon/MICA/blob/74885b9bdf2d1bc66158eaf43091b1221cc7bfdb/demo.py#L112

```python
app = FaceAnalysis(name='antelopev2', root=insightface_folder, providers=['CUDAExecutionProvider'])
```

**Comment by PRADEEPRAJKB** [comment]
> Hey, the `install.sh` will download it automatically. You can also download them from here:
> 
> [antelopev2.zip](https://keeper.mpdl.mpg.de/f/2d58b7fed5a74cb5be83/?dl=1) [buffalo_l.zip](https://keeper.mpdl.mpg.de/f/8faabd353cfc457fa5c5/?dl=1)
> 
> then you need to unzip them and place in `~/.insightface/models/`

Just have a question, where do I find the `Install.sh`
