### ISSUE TITLE
Possible typing error at line 149 of the "environment.yml" file

### ISSUE THREAD

**Issue by biesseck** [Zielon/MICA#21]
While trying to install and create the MICA env by running the "_install.sh_" script, conda showed the following error when running "_conda env create -f environment.yml_":

```
Installing conda env...
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - pytorch3d-0.7.0-py38_cu113_pyt1110 (line 149)
```

SOLUTION: use **pytorch3d=0.7.0=py38_cu113_pyt1110** (replace the "-" by "=").

**Comment by Zielon** [comment]
Nice catch. Thank you! Already fixed.
