### ISSUE TITLE
the performance based on DECA and MICA

### ISSUE THREAD

**Issue by liushengtong-nreal** [Zielon/MICA#25]
In your paper table5 shows, why DECA-based methods lead to huge overfitting when using fine-tuning of partial layers or entire pipeline, but the MICA can get better performace?  thanks

**Comment by Zielon** [comment]
I don't understand the question. If this is what you are asking, DECA needs more data to train.

**Comment by liushengtong-nreal** [comment]
Sorry, I didn't ask clearly.  Why the red line get better performace than the blue line, but the green line get worse performance than the yellow line?  
You state in your research that this may be due to fine-tuning of partial layers or entire pipeline leads to huge overfitting of the training data。Why does this happen to DECA but not to MICA？ 

![screenshot-20220914-114257](https://user-images.githubusercontent.com/108505924/190054647-5cd8898d-0b28-434b-9f54-ea0371106a0f.png)
