### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by liushengtong-nreal** [Zielon/MICA#29]
Why the red line get better performace than the blue line, but the green line get worse performance than the yellow line?
You state in your research that this may be due to fine-tuning of partial layers or entire pipeline leads to huge overfitting of the training data。Why does this happen to DECA but not to MICA？

![screenshot-20220914-114257](https://user-images.githubusercontent.com/108505924/190540203-f9900877-55d6-4582-8ad4-c0cbf0317099.png)

**Comment by Zielon** [comment]
DECA has a decoder that regresses not only the shape but multiple other parameters. Thus refining it is not as straightforward as in the case of ArcFace.
