### ISSUE TITLE
How do we change the output shape of 3D face? 

### ISSUE THREAD

**Issue by hoangNguyen210** [Zielon/MICA#30]
Hi, I have used your **demo.py** code. The 3D face output has fixed numbers of  5023 verticals and  9976 heads in the .obj file. How can we change the number of verticals and heads in this output file? As I want to have a higher resolution output.

Also, can we still use the pre-trained model if we change these parameters? 

Thanks

**Comment by Zielon** [comment]
You can subdivide the output mesh for instance. However, the original mesh will always be in this resolution since it is bounded to the FLAME model.
