### ISSUE TITLE
Expression parameters

### ISSUE THREAD

**Issue by AyushP123** [Zielon/MICA#32]
Hi,

I wanted to ask if it is possible to add expression parameters generated by DECA to MICA. I see that the expression parameters generated by DECA are a 50-dimensional vector whereas for MICA it is a 100-dimensional vector.

**Comment by Zielon** [comment]
MICA is not using expressions parameters, you can just take the shape code from MICA, and set in Flame class (or your config) how many expressions and shape params you want to use. This will work for the Flame generator.
