### ISSUE TITLE
is it possible to improve your code in order to generate 608 dense landmark

### ISSUE THREAD

**Issue by maemoKKK** [Zielon/MICA#39]
before by hand, I want to know if your code can be used as 608 dense landmark generator like the paper [3D Face Reconstruction with Dense Landmarks]. 

I notice in your code, here is blendshape or someting like this, and in your paper, your code can generate the same facial pose 3D reconstruction.

I want to know whether your code can be used to 608 facial dense landmarks. if it cans ，I will take part in develop.

**Comment by Zielon** [comment]
I do not plan to add new functionalities. Thank you.
