### ISSUE TITLE
Is there an demo on the video using face tracking?

### ISSUE THREAD

**Issue by Koruvika** [Zielon/MICA#41]

**Comment by Zielon** [comment]
Hi, currently the code is not available, unfortunately. But we are thinking of releasing it.

**Comment by luchaoqi** [comment]
+1 would be great if we can get the code for motion tracking

**Comment by sidk99** [comment]
+1

**Comment by Zielon** [comment]
https://github.com/Zielon/metrical-tracker the tracker is now released.
