### ISSUE TITLE
flame-fitting release

### ISSUE THREAD

**Issue by littlePrince126** [Zielon/MICA#5]
Thanks for your great work.  I am not sure if you use the fitting way by [Rubikplayer/flame-fitting](https://github.com/Rubikplayer/flame-fitting). If you have a better way to fit 3D scan with FLAME, could you share the flame-fitting code? Thank you very much.

**Comment by Zielon** [comment]
We used a modified version of `flame-fitting` repo. Unfortunately, it is not available.

**Comment by SuperStacie** [comment]
Hi, I assume the landmark marking step is free of manual labeling in your modified version. May I know how to make the process fully automative? Thanks!

**Comment by Zielon** [comment]
https://github.com/Zielon/metrical-tracker
