### ISSUE TITLE
 No such file or directory: '/content/MICA/utils/../data/FLAME2020/generic_model.pkl'

### ISSUE THREAD

**Issue by profgandhi** [Zielon/MICA#56]
I did the steps, But its showing me this error?

**Comment by fantasy-byakuya** [comment]
I have the same problem, this path can be modified to use, but I can not find this file, have you solved this problem

**Comment by Zielon** [comment]
Hey, you need to download the model from here https://flame.is.tue.mpg.de/.

**Comment by fantasy-byakuya** [comment]
> Hey, you need to download the model from here https://flame.is.tue.mpg.de/.

FLAME 2020 (fixed mouth, improved expressions, more data)，I found it. I missed it. Thank you！
