### ISSUE TITLE
Installation issues - dependency conflicts on environment.yml

### ISSUE THREAD

**Issue by luizgh** [Zielon/MICA#60]
Hi!

Thanks for putting together an easy-to-use installation script, that's very helpful.
I would like to let you know that the current environment.yml file has some conflicts. If you try to create a conda environment with the current version it complains about this:

> The conflict is caused by:
    The user requested protobuf==3.20.0
    google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5

I was able to get it working by specifying protobuf 3.20.2, and in turn I had to upgrade onnx to 1.13.0.

**Comment by Zielon** [comment]
Thank you. I updated the file.
