### ISSUE TITLE
arcface_pretrained_model

### ISSUE THREAD

**Issue by zhumeichoubao** [Zielon/MICA#62]
Thanks for your nice work
How do I find the arcface_pretrained_model(backbone100.pth) used by MICA train, can you provide a download link.
hope to receive your answer，thank you very much!

**Comment by Zielon** [comment]
You can find it here: https://onedrive.live.com/?authkey=%21AFZjr283nwZHqbA&id=4A83B6B633B029CC%215577&cid=4A83B6B633B029CC. I used R100 backbone.
