### ISSUE TITLE
FLAME-fitting

### ISSUE THREAD

**Issue by zhumeichoubao** [Zielon/MICA#64]
Thx for your great work!
I want to fit other 3D scans to FLAME to enhance the MICA's training dataset, could you share the MICA's flame-fitting code? 

Thanks a lot!

**Comment by Zielon** [comment]
Hello, unfortunately this code is not public.

**Comment by CIntellifusion** [comment]
Exceuse me. Do you have any advice about get registrations of FLAME from 3D scans with expressions？
