### ISSUE TITLE
Confirmation of output

### ISSUE THREAD

**Issue by Inferencer** [Zielon/MICA#65]
Can I just confirm a couple of things
the first being the blue face mask with eye holes as shown in the demo video is outputted or are they filled in as shown in the project page comparisons?

the second part is can I put this in a 3D application like Blender with the tracking/ animation data or is it limited to a third party viewer like a flame render engine ?

**Comment by Schizo00** [comment]
I have the same question. Please explain a bit more on what the output of the model is

**Comment by Zielon** [comment]
The model outputs shape coefficients for the FALME model and the mesh itself. You can use the mash in any viewer. The blue mask is from the demo only and is obtained using the tracker, not MICA.
