### ISSUE TITLE
Do you plan to publish your face tracking algorithm?

### ISSUE THREAD

**Issue by VisionaryMind** [Zielon/MICA#7]
I am already using DECA and EMOCA for face tracking and was hoping this was an improvement over both. Unfortunately, this project only implements static head generation with no facial tracking. Further, the output mesh is not in the original orientation (as observed in the input images). For now, both DECA and EMOCA are superior for the purpose of capturing temporal facial data. I see in your video that you are doing it with MICA as well, so clearly, there is some potential here. As for static head generation, negligible difference over DECA. Please consider sharing the rest of your code.

**Comment by Zielon** [comment]
Unfortunately, currently, this is out of scope.
