### ISSUE TITLE
Why we need multi  "1000" when calculating the metrical error ?

### ISSUE THREAD

**Issue by lililuya** [Zielon/MICA#70]
Hi, thanks for your great works. I am confused about a detail when calculating metrical error(mm). Just at https://github.com/Zielon/MICA/blob/8de9025ee155f208f4a4aed61ade303237f9b1db/demo.py#L136, why the vertices need multiply 1000, is the unit of the flame vertices is 1mm/1000? Looking for your reply!

**Comment by Zielon** [comment]
We convert from meters to millimetres. FLAME is originally in meters.

**Comment by lililuya** [comment]
> We convert from meters to millimetres. FLAME is originally in meters.

Thanks!

**Comment by fantasy-byakuya** [comment]
萨姆兄弟，你知道generic_model.pkl这个文件在哪吗，我在复现过程中发现，没有仓库中没有这个文件，也没有找到去哪获取它TOT
